#pragma once

#define SCREEN_PIXEL (6)
#define SCREEN_WIDTH (160)
#define SCREEN_HEIGHT (120)
#define SCREEN_PHYSICAL_WIDTH (SCREEN_WIDTH * SCREEN_PIXEL)
#define SCREEN_PHYSICAL_HEIGHT (SCREEN_HEIGHT * SCREEN_PIXEL)